import type { ModelingBundle, ModelingCase } from "@/server/modeling-demo";
import { displayModelValue as value, getCaseGoal, type ModelingReviewDraft } from "@/domain/modeling-workflow";
import styles from "@/app/modeling/workflow.module.css";

const reviewLabels = { PENDING: "검토 중", NEEDS_INFORMATION: "자료 보완 필요", READY_FOR_REVIEW: "기관 검토 준비", HOLD: "보류" };

export function ModelingInstitutionReport({ selectedCase, initialCase, reevaluation, modelVersion, draft }: {
  selectedCase: ModelingCase; initialCase: ModelingCase; reevaluation: ModelingBundle["reevaluation"]; modelVersion: string; draft: ModelingReviewDraft;
}) {
  const isFollowup = selectedCase.caseId === reevaluation.afterCase;
  const goal = getCaseGoal(initialCase);
  const missing = selectedCase.features.filter((feature) => feature.usedInScore && ["MISSING", "REFUSED", "UNDECIDED"].includes(feature.status));
  const excerpts = selectedCase.interviewConversion.items.filter((item) => item.evidencePresent && item.evidenceText);
  const keyFeatures = ["fin_sales_avg_3m", "fin_net_cashflow_avg_3m", "biz_operating_day_count_avg_3m", "fin_cash_buffer_days_est"].map((code) => selectedCase.features.find((feature) => feature.code === code)).filter((feature) => feature !== undefined);
  return <article id="modeling-review-report" className={styles.report}>
    <header className={styles.heading}><span>동행금융 · 금융기관 검토용 자료</span><h2>{selectedCase.title}</h2><p>{isFollowup ? "후속 자료 반영본" : "최초 분석본"} · {selectedCase.caseId} · {reviewLabels[draft.disposition]}</p><p>Competition Demo / Synthetic Data</p></header>
    <div className={styles.dossierGrid} aria-label="금융기관 검토 핵심 내용">
      <article><span>01 · 상황과 변화 원인</span><h3>사업 현황</h3><p>{selectedCase.summary}</p>{excerpts[0] ? <blockquote>{excerpts[0].evidenceText}<small>합성 인터뷰 원문 · {excerpts[0].evidenceId}</small></blockquote> : <p>해당 시점에 확보한 인터뷰 원문이 없습니다.</p>}</article>
      <article><span>02 · 현금흐름과 운영</span><h3>주요 변수</h3><dl>{keyFeatures.map((feature) => <div key={feature.code}><dt>{feature.label}</dt><dd>{value(feature.value, feature.code)}<small>{feature.sourceLabel} · {feature.status}</small></dd></div>)}</dl><p className={styles.note}>사업 운영 지표이며 상환 가능액을 산정한 값은 아닙니다.</p></article>
      <article><span>03 · 자료와 확인 범위</span><h3>검토자료 구성</h3><p>전체 변수 {selectedCase.featureSummary.total}개 중 값이 있는 변수 {selectedCase.featureSummary.valueCount}개</p><ul>{Object.entries(selectedCase.featureSummary.statusCounts).map(([state, count]) => <li key={state}>{state} · {count}개</li>)}</ul><p className={styles.note}>자료의 존재와 원본 증빙의 진위 확인은 구분합니다.</p></article>
    </div>
    <section><h3>1. 평가 결과와 산출 근거</h3><div className={styles.reportAxes}>{(["currentSituation", "improvement"] as const).map((name) => { const axis = selectedCase.scorecard[name]; return <div className={styles.axis} key={name}><span>{name === "currentSituation" ? "현재 상황" : "개선가능성"}</span><strong>{value(axis.score)}<small> / 100</small></strong><p>{axis.accounting.earnedPoints} ÷ {axis.accounting.availablePoints} × 100 · {axis.itemsUsed}/{axis.itemsTotal}항목 반영</p><p>{axis.note}</p></div>; })}</div><p>기존 규칙 모형의 사업·행동 지표입니다. 신용등급·연체확률·대출 승인 결과를 산출한 값은 아닙니다.</p>
      <div className={styles.tableWrap}><table><caption>평가항목 → 사용 변수 → 원천자료</caption><thead><tr><th>평가항목</th><th>반영값</th><th>산출 이유와 연결 근거</th></tr></thead><tbody>{(["currentSituation", "improvement"] as const).flatMap((axis) => selectedCase.scorecard[axis].items.map((item) => <tr key={`${axis}-${item.name}`}><th scope="row">{item.name}<small>{axis === "currentSituation" ? "현재 상황" : "개선가능성"}</small></th><td>{item.excluded ? "계산 제외" : `${item.points} / ${item.maxPoints}`}</td><td><p>{item.note || item.band}</p><details><summary>사용 변수와 근거 {item.lineage.length}개</summary>{item.lineage.map((line, index) => <div className={styles.sourceLine} key={`${line.feature}-${index}`}><strong>{line.label} · {value(line.value, line.feature)}</strong><code>{line.feature}</code><small>{line.sourceLabel} · {line.status} · {line.evidenceRefs.join(", ") || "연결 자료 없음"}</small>{excerpts.filter((entry) => entry.evidenceId && line.evidenceRefs.includes(entry.evidenceId)).map((entry) => <blockquote key={entry.feature}>{entry.evidenceText}</blockquote>)}</div>)}</details></td></tr>))}</tbody></table></div>
    </section>
    <section><h3>2. 인터뷰에서 추가된 정보</h3><p>매출이나 거래값만으로 설명하기 어려운 사정을 원문과 함께 확인합니다.</p>{excerpts.length ? <div className={styles.tableWrap}><table><thead><tr><th>구조화한 정보</th><th>확인한 값</th><th>원문 근거</th></tr></thead><tbody>{excerpts.map((entry) => <tr key={entry.feature}><th scope="row">{entry.label}<code>{entry.feature}</code></th><td>{value(entry.value, entry.feature)}<small>{entry.status}</small></td><td><blockquote>{entry.evidenceText}</blockquote><small>{entry.evidenceId}</small></td></tr>)}</tbody></table></div> : <p>이 자료에 포함된 새 인터뷰 원문이 없습니다. 과거 답변을 현재 확인값으로 채우지 않습니다.</p>}</section>
    <section><h3>3. 목표와 수행자료</h3><p>{goal.feature?.label ?? "목표 미확인"}: {value(goal.feature?.value, goal.feature?.code)} → 목표 {value(goal.target?.value, goal.feature?.code)} · {value(goal.horizon?.value, "horizon_days")}</p><p>기록된 계획: {value(goal.action?.value)} · 예산 {value(goal.budget?.value, "budget")} · 제약 {value(goal.blocker?.value)}</p><p>담당자 확인: 목표 {draft.goalConfirmed ? "확인" : "대기"} / 수행자료 {draft.recordsReviewed ? "확인" : "대기"}</p>{isFollowup ? <><p>{reevaluation.baselineAsOf} → {reevaluation.followupAsOf} · 합성 후속 거래자료 {reevaluation.monthlyRecords.length}개월</p><p>{reevaluation.measurementRule} · 최근 값 {value(reevaluation.after, reevaluation.goalFeature)} · {reevaluation.reached === true ? "목표 충족" : reevaluation.reached === false ? "목표 미달" : "판정 보류"}</p><div className={styles.tableWrap}><table><thead><tr><th>기간</th><th>카드매출</th><th>영업일</th><th>목표 측정 포함</th></tr></thead><tbody>{reevaluation.monthlyRecords.map((row) => <tr key={row.month}><td>{row.month}</td><td>{value(row.sales, "sales_avg")}</td><td>{row.operatingDays}일</td><td>{row.includedInGoal ? "최근 3개월" : "경과 기록"}</td></tr>)}</tbody></table></div><p className={styles.boundary}>최초와 후속 분석의 반영 항목·분모가 다릅니다. 점수 변화는 신용 개선률을 뜻하지 않으며 목표 달성을 가산점으로 처리하지 않습니다.</p></> : <p>현재 선택한 자료는 최초 분석본입니다. 후속 결과가 있는 사례는 검토 사례에서 ‘재평가’ 자료를 선택할 수 있습니다.</p>}</section>
    <section><h3>4. 자료 출처와 보완할 항목</h3><div className={styles.tableWrap}><table><thead><tr><th>원천자료</th><th>변수</th><th>값 확보</th><th>출처 범위</th></tr></thead><tbody>{selectedCase.sourceSummary.map((source) => <tr key={source.source}><th>{source.sourceLabel}</th><td>{source.featureCount}</td><td>{source.valueCount}</td><td>합성 사례 · {source.source}</td></tr>)}</tbody></table></div><p>평가에 사용되는 변수 중 {missing.length}개가 미확인·답변 거절·미결정 상태입니다.</p><ul className={styles.pending}>{missing.map((feature) => <li key={feature.code}>{feature.label} · {feature.status}</li>)}</ul><p>서류 원본, 기간과 출처, 기관별 제출 요건은 담당자가 추가 확인합니다.</p></section>
    <section><h3>5. 담당자 검토 의견</h3><p><strong>{reviewLabels[draft.disposition]}</strong>{draft.updatedAt && <small> · {new Date(draft.updatedAt).toLocaleString("ko-KR", { timeZone: "Asia/Seoul" })}</small>}</p><p className={styles.savedNote}>{draft.note || "아직 작성한 검토 의견이 없습니다."}</p><p className={styles.note}>담당자 메모는 이 브라우저의 검토 기록입니다. 원천자료나 평가값에 반영되지 않습니다.</p></section>
    <footer>자료 기준: {modelVersion} · {selectedCase.caseId} · 합성 데이터. 기관 전송·대출 신청 또는 승인 판단을 수행한 자료가 아닙니다.</footer>
  </article>;
}
