import type { ModelingBundle, ModelingCase } from "@/server/modeling-demo";
import { displayModelValue as value, getCaseGoal, type ModelingReviewDraft } from "@/domain/modeling-workflow";
import styles from "@/app/institution-review.module.css";
import reportStyles from "@/app/modeling/workflow.module.css";

export const MODELING_REVIEW_LABELS = { PENDING: "검토 중", NEEDS_INFORMATION: "자료 보완 필요", READY_FOR_REVIEW: "기관 검토 준비", HOLD: "보류" };
type ReportProps = {
  selectedCase: ModelingCase; initialCase: ModelingCase; reevaluation: ModelingBundle["reevaluation"]; modelVersion: string; draft: ModelingReviewDraft;
  section?: "overview" | "evidence" | "plan" | "opinion" | "all";
};

/** The same sections serve the work area and the complete printable document. */
export function ModelingInstitutionReport({ selectedCase, initialCase, reevaluation, modelVersion, draft, section = "all" }: ReportProps) {
  const isFollowup = selectedCase.caseId === reevaluation.afterCase;
  const goal = getCaseGoal(initialCase);
  const missing = selectedCase.features.filter((feature) => feature.usedInScore && ["MISSING", "REFUSED", "UNDECIDED"].includes(feature.status));
  const excerpts = selectedCase.interviewConversion.items.filter((item) => item.evidencePresent && item.evidenceText);
  const keyFeatures = ["fin_sales_avg_3m", "fin_net_cashflow_avg_3m", "biz_operating_day_count_avg_3m", "fin_cash_buffer_days_est"].map((code) => selectedCase.features.find((feature) => feature.code === code)).filter((feature) => feature !== undefined);
  const show = (name: string) => section === "all" || section === name;
  const content = <>
    {show("overview") && <section className={styles.section}>
      <div className={styles.overviewHero}><h2>사업 현황</h2><p className={styles.sectionLead}>{selectedCase.summary}</p>{excerpts[0] ? <blockquote>{excerpts[0].evidenceText}<small className={styles.muted}> · 인터뷰 진술</small></blockquote> : <p className={styles.muted}>해당 시점에 확보한 인터뷰 원문이 없습니다.</p>}</div>
      <h3>주요 변수</h3><dl className={styles.facts}>{keyFeatures.map((feature) => <div key={feature.code}><dt>{feature.label}</dt><dd>{value(feature.value, feature.code)}<small>{feature.sourceLabel} · {feature.status}</small></dd></div>)}</dl>
      <div className={styles.axes}>{(["currentSituation", "improvement"] as const).map((name) => { const axis = selectedCase.scorecard[name]; return <article key={name}><span>{name === "currentSituation" ? "현재 상황" : "개선가능성"}</span><strong>{value(axis.score)}<small> / 100</small></strong><p>{axis.accounting.earnedPoints} ÷ {axis.accounting.availablePoints} × 100 · {axis.itemsUsed}/{axis.itemsTotal}항목 반영</p>{axis.note && <p>{axis.note}</p>}</article>; })}</div>
      <p className={styles.boundary}>합성 거래자료에 기존 규칙을 적용한 사업·행동 지표입니다. 신용등급이나 대출 승인 결과, 상환 가능액을 산정한 값이 아닙니다.</p>
    </section>}
    {show("evidence") && <>
      <section className={styles.section}><h2>평가 결과와 산출 근거</h2><p className={styles.sectionLead}>각 항목에서 사용 변수와 연결 원문을 확인할 수 있습니다.</p>
        <div className={styles.tableWrap}><table><caption>평가항목 → 사용 변수 → 원천자료</caption><colgroup><col style={{ width: "25%" }} /><col style={{ width: "16%" }} /><col /></colgroup><thead><tr><th>평가항목</th><th>반영값</th><th>산출 이유와 연결 근거</th></tr></thead><tbody>{(["currentSituation", "improvement"] as const).flatMap((axis) => selectedCase.scorecard[axis].items.map((item) => <tr key={`${axis}-${item.name}`}><th scope="row">{item.name}<small>{axis === "currentSituation" ? "현재 상황" : "개선가능성"}</small></th><td>{item.excluded ? "계산 제외" : `${item.points} / ${item.maxPoints}`}</td><td>{item.note || item.band}<details><summary>사용 변수와 근거 {item.lineage.length}개</summary>{item.lineage.map((line, index) => <div className={styles.trace} key={`${line.feature}-${index}`}><strong>{line.label} · {value(line.value, line.feature)}</strong><code>{line.feature}</code><small>{line.sourceLabel} · {line.status} · {line.evidenceRefs.join(", ") || "연결 자료 없음"}</small>{excerpts.filter((entry) => entry.evidenceId && line.evidenceRefs.includes(entry.evidenceId)).map((entry) => <blockquote key={entry.feature}>{entry.evidenceText}</blockquote>)}</div>)}</details></td></tr>))}</tbody></table></div>
      </section>
      <section className={styles.section}><h3>인터뷰에서 추가된 정보</h3>{excerpts.length ? <div className={styles.tableWrap}><table><thead><tr><th>구조화한 정보</th><th>확인한 값</th><th>원문 근거</th></tr></thead><tbody>{excerpts.map((entry) => <tr key={entry.feature}><th scope="row">{entry.label}<code>{entry.feature}</code></th><td>{value(entry.value, entry.feature)}<small>{entry.status}</small></td><td>{entry.evidenceText}<small>{entry.evidenceId}</small></td></tr>)}</tbody></table></div> : <p>이 자료에 포함된 새 인터뷰 원문이 없습니다. 과거 답변을 현재 확인값으로 채우지 않습니다.</p>}</section>
      <section className={styles.section}><h3>검토자료 구성</h3><p className={styles.muted}>전체 변수 {selectedCase.featureSummary.total}개 · 값이 있는 변수 {selectedCase.featureSummary.valueCount}개</p><ul className={styles.pending}>{Object.entries(selectedCase.featureSummary.statusCounts).map(([state, count]) => <li key={state}>{state} · {count}개</li>)}</ul><div className={styles.tableWrap}><table><thead><tr><th>원천자료</th><th>변수</th><th>값 확보</th><th>출처 범위</th></tr></thead><tbody>{selectedCase.sourceSummary.map((source) => <tr key={source.source}><th>{source.sourceLabel}</th><td>{source.featureCount}</td><td>{source.valueCount}</td><td>합성 사례 · {source.source}</td></tr>)}</tbody></table></div><p>평가에 사용되는 변수 중 {missing.length}개가 미확인·답변 거절·미결정 상태입니다.</p><ul className={styles.pending}>{missing.map((feature) => <li key={feature.code}>{feature.label} · {feature.status}</li>)}</ul><p className={styles.muted}>서류 원본, 자료의 기간·출처와 기관별 제출 요건은 별도로 확인합니다.</p></section>
    </>}
    {show("plan") && <section className={styles.section}><h2>목표와 수행자료</h2><p className={styles.sectionLead}>처음 정한 목표와 이후 확보한 자료를 함께 검토합니다.</p><dl className={styles.facts}><div><dt>{goal.feature?.label ?? "목표 미확인"} · 최초</dt><dd>{value(goal.feature?.value, goal.feature?.code)}</dd></div><div><dt>목표 · {value(goal.horizon?.value, "horizon_days")}</dt><dd>{value(goal.target?.value, goal.feature?.code)}</dd></div></dl><p>기록된 계획: {value(goal.action?.value)} · 예산 {value(goal.budget?.value, "budget")} · 제약 {value(goal.blocker?.value)}</p><p className={styles.muted}>담당자 확인: 목표 {draft.goalConfirmed ? "확인" : "대기"} / 수행자료 {draft.recordsReviewed ? "확인" : "대기"}</p>{isFollowup ? <><h3>6개월 후 확인한 결과</h3><p>{reevaluation.baselineAsOf} → {reevaluation.followupAsOf} · 합성 후속 거래자료 {reevaluation.monthlyRecords.length}개월</p><p>{reevaluation.measurementRule} · 최근 값 {value(reevaluation.after, reevaluation.goalFeature)} · {reevaluation.reached === true ? "목표 충족" : reevaluation.reached === false ? "목표 미달" : "판정 보류"}</p><div className={styles.tableWrap}><table><thead><tr><th>기간</th><th>카드매출</th><th>영업일</th><th>목표 측정 포함</th></tr></thead><tbody>{reevaluation.monthlyRecords.map((row) => <tr key={row.month}><td>{row.month}</td><td>{value(row.sales, "sales_avg")}</td><td>{row.operatingDays}일</td><td>{row.includedInGoal ? "최근 3개월" : "경과 기록"}</td></tr>)}</tbody></table></div><p className={styles.boundary}>최초와 후속 분석의 반영 항목·분모가 다릅니다. 점수 변화는 신용 개선률을 뜻하지 않으며 목표 달성을 가산점으로 처리하지 않습니다.</p></> : <p className={styles.muted}>현재는 최초 분석본입니다. 후속 결과가 있는 사례는 상단의 ‘6개월 후’에서 확인할 수 있습니다.</p>}</section>}
    {show("opinion") && <section className={styles.section}><h3>담당자 검토 의견</h3><span className={styles.badge}>{MODELING_REVIEW_LABELS[draft.disposition]}</span><p className={styles.savedNote}>{draft.note || "아직 작성한 검토 의견이 없습니다."}</p>{draft.updatedAt && <p className={styles.muted}>{new Date(draft.updatedAt).toLocaleString("ko-KR", { timeZone: "Asia/Seoul" })} 저장</p>}</section>}
  </>;
  return section === "all" ? <article id="modeling-review-report" className={reportStyles.report}><header className={reportStyles.heading}><span>동행금융 · 금융기관 검토용 자료</span><h2>{selectedCase.title}</h2><p>{isFollowup ? "후속 자료 반영본" : "최초 분석본"} · {selectedCase.caseId}</p><p>Competition Demo / Synthetic Data</p></header>{content}<footer>자료 기준: {modelVersion} · {selectedCase.caseId} · 합성 데이터. 검토 메모는 이 브라우저에 저장하며 평가값에 반영하지 않습니다. 기관 전송·대출 신청 또는 승인 판단을 수행한 자료가 아닙니다.</footer></article> : content;
}
